[env]
platform = atmelavr
board = nanoatmega328

[env:arduino-framework]
framework = arduino
monitor_speed = 9600
build_src_filter = +<arduino-framework/>

[env:arduino-fw-v2]
framework = arduino
monitor_speed = 9600
build_src_filter = +<arduino-fw-v2/>

[env:bare-metal]
platform = atmelavr
board = nanoatmega328
board_build.f_cpu = 16000000L
build_src_filter = +<bare-metal/>